services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_NAME=:80
      - DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db
      - APP_ENV=dev
      - APP_DEBUG=1
      - APP_SECRET=ChangeMe123!
